spring.application.name=OnlineElectronicStore
server.port=9090
#database configuration
spring.datasource.url=jdbc:mysql://localhost:3306/electronic_store
spring.datasource.username=root
spring.datasource.password=Kushwaha@123
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

#jpa and hibernate configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

server.servlet.context-path=/api

#max allowed size for single upload file
spring.servlet.multipart.max-file-size=10MB
Maximum allowed size for a complete multipart/form-data request
spring.servlet.multipart.max-request-size=10MB

logging.level.org.hibernate.SQL=DEBUG

#path  config
user.profile.image.path= /images/users/
product.image.path= /images/products/


